spring:
  application:
    name: shop-service
  boot:
    admin:
      client:
        enabled: true
        instance:
          name: shop-service
          service-host-type: ip
        url:
          - http://localhost:8086
  datasource:
    url: jdbc:postgresql://localhost:5432/secondproject_server_database
    username: postgres
    password: glhf5561783742
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      -product
      -favorite_product
  profiles:
    active:
      - postgres
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/secondproject
      client:
        registration:
          keycloak:
            clientId: shop-service-metrics-client
            clientSecret: CyYfE0ooOFewdKUQmp3El1KBob3qiuwe
            authorizationGrantType: client_credentials
            scope:
              - metrics_server
        provider:
          keycloak:
            issuerUri: http://localhost:8083/realms/secondproject

springdoc:
  swagger-ui:
    oauth:
      client-id: shop-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
server:
  port: 8081
logging:
  level:
    sql: info

keycloak:
  uri: http://localhost:8083
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
