spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/secondproject_server_database
    username: postgres
    password: glhf5561783742
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      -product
      -favorite_product
  profiles:
    active:
      - postgres
  jpa:
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/secondproject
springdoc:
  swagger-ui:
    oauth:
      client-id: shop-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
server:
  port: 8081
logging:
  level:
    sql: info
keycloak:
  uri: http://localhost:8083


      