server:
  port: 8086
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/secondproject
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/secondproject
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: eJuctbzpC09WcWZX5NZnv0eth8vXferD
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            clientId: admin-service
            clientSecret: eJuctbzpC09WcWZX5NZnv0eth8vXferD
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus