version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: secondproject_keycloak_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glhf5561783742
    networks:
      - secondproject
  keycloak:
    container_name: keycloak-secondproject
    image: quay.io/keycloak/keycloak:25.0.4
    command:
      - start-dev
    links:
      - postgres
    ports:
      - "8083:8083"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: glhf5561783742
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_database
      KC_HOSTNAME: localhost
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - secondproject
