services:
  # Postgres
  postgres:
    networks:
      - secondproject_network
    image: postgres:latest
    environment:
      POSTGRES_DB: secondproject_server_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: glhf5561783742
      TZ: UTC
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  # MongoDB
  mongodb:
    networks:
      - secondproject_network
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  # Keycloak
  keycloak:
    networks:
      - secondproject_network
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8083:8083"
    command: [ "start-dev", "--http-port=8083" ]
  # admin-server
  admin-server:
    networks:
      - secondproject_network
    build:
      context: ./admin-server
    ports:
      - "8086:8086"
  # manager-application
  manager-application:
    networks:
      - secondproject_network
    build:
      context: ./manager-application
    ports:
      - "8082:8082"
  # reactive-customer-application
  reactive-customer-application:
    networks:
      - secondproject_network
    build:
      context: ./reactive-customer-application
    ports:
      - "8084:8084"
  # reactive-feedback-service
  reactive-feedback-service:
    networks:
      - secondproject_network
    build:
      context: ./reactive-feedback-service
    depends_on:
      - mongodb
    ports:
      - "8085:8085"
  # shop-service
  shop-service:
    networks:
      - secondproject_network
    build:
      context: ./shop-service
    depends_on:
      - postgres
    ports:
      - "8081:8081"
volumes:
  pg_data:
  mongo_data:
networks:
  secondproject_network: