spring:
  boot:
    admin:
      client:
        url: http://localhost:8086
        instance:
          name: manager-application
          service-host-type: ip
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/secondproject_client_database
    username: postgres
    password: glhf5561783742
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - manager
  profiles:
    active:
      - postgres
  jpa:
    show-sql: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8083/realms/secondproject
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-module
            client-secret: AtEXiFUCk5I2if9b4pN4UQBDCEBhr4To
            scope:
              - openid
              - edit_products_catalogue
              - microprofile-jwt
          metrics:
            provider: keycloak
            client-id: manager-application-metrics-client
            client-secret: CFyhN2jF9rNEIDlDRkRytk80vlQxyKAb
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/secondproject
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 8082
logging:
  level:
    sql: info

shop:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak
